version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerconfig/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: production
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 8080:8080
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0" --encore-args="--port 8080"

volumes:
  postgres_volume: